tinyblog/urls.py
from django.urls import path
from . import views


app_name = 'tinyblog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('entry/<int:pk>', views.DetailView.as_view(), name='entry'),
    path('add/', views.CreateView.as_view(), name='add'),
    path('edit/<int:pk>', views.EditView.as_view(), name='edit'),
    path('del/<int:pk>', views.DeleteView.as_view(), name='delete'),
]

tinyblog/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=100)
    entry = models.TextField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

tinyblog/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'entry')
        widgets = {
            'title': forms.TextInput(attrs=dict(placeholder='タイトル')),
            'entry': forms.Textarea(attrs=dict(rows=8)),
        }

tinyblog/views.py
from django.views import generic
from django.urls import reverse_lazy

from .models import Article
from .forms import ArticleForm


class IndexView(generic.ListView):
    model = Article


class DetailView(generic.DetailView):
    model = Article


class CreateView(generic.CreateView):
    model = Article
    form_class = ArticleForm
    success_url = reverse_lazy('tinyblog:index')


class EditView(generic.UpdateView):
    model = Article
    form_class = ArticleForm
    success_url = reverse_lazy('tinyblog:index')

class DeleteView(generic.DeleteView):
    model = Article
    success_url = reverse_lazy('tinyblog:index')

tinyblog/templates/tinyblog/_base.html
{% load static %}
<!doctype html>
<html>
  <head>
    <title>
      {% block title %}
      {% endblock %}
    </title>
  </head>

  <body>
    <div>
      {% block content %}
      {% endblock %}
    </div>
  </body>

</html>

tinyblog/templates/tinyblog/article_confirm_delete.html
{% extends "tinyblog/_base.html" %}

{% block title %}
削除の確認
{% endblock %}

{% block content %}
<h1>データの削除</h1>
<p>このデータを削除します。よろしいですか。</p>
<form action="" method="post">
  {% csrf_token %}
  <p>Title: {{ article.title }}</p>
  <p>Entry: {{ article.entry|linebreaksbr }}</p>
  <button type="submit">削除</button>
  <a href="{% url 'tinyblog:index' %}">キャンセル</a>
</form>
{% endblock %}

tinyblog/templates/tinyblog/article_detail.html
{% extends "tinyblog/_base.html" %}

{% block title %}
{{ article.title }}
{% endblock %}

{% block content %}
<h1>{{ article.title }}</h1>
<div>
  <p>{{ article.entry|linebreaksbr }}</p>
  <a href="{% url 'tinyblog:index' %}">戻る</a>
</div>
{% endblock %}

tinyblog/templates/tinyblog/article_form.html
{% extends "tinyblog/_base.html" %}

{% block title %}
記事の入力・更新
{% endblock %}

{% block content %}
{{ form.certifications.errors }}
<h1>記事入力</h1>
<div>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">投稿する</button>
    <button onclick="location.href={% url 'tinyblog:index' %}">中止</button>
  </form>
</div>
{% endblock %}

tinyblog/templates/tinyblog/article_list.html
{% extends "tinyblog/_base.html" %}

{% block title %}
記事のリスト
{% endblock %}

{% block content %}
<ul>
  {% for article in article_list %}
  <li>
    {{ article.title }}
    <a href="{% url 'tinyblog:entry' article.id %}">表示</a>
    <a href="{% url 'tinyblog:edit' article.id %}">変更</a>
    <a href="{% url 'tinyblog:delete' article.id %}">削除</a>
  </li>
  {% endfor %}
</ul>

<p><a href="{% url 'tinyblog:add' %}">新規投稿</a></p>
{% endblock %}